### Base
FROM node:16-alpine as base

# Enable Node.js optimisation
ENV NODE_ENV=development
RUN mkdir /app
EXPOSE 8001
WORKDIR /app
USER root
COPY  package.json yarn.lock ./
RUN yarn
COPY . .

CMD yarn start:dev






