### Base
FROM node:16-alpine as base

# Enable Node.js optimisation
ENV NODE_ENV=development
RUN mkdir /app
EXPOSE 8001
EXPOSE 8101
WORKDIR /app
USER root
COPY  package.json ./
RUN npm install -f
COPY . .

CMD npm run start:dev






