version: '3.7'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-gateway
    tty: true
    volumes:
      - ./ApiGateway/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    networks:
      - backend-network
    restart: unless-stopped
  user-services:
    build:
      context: ./UserService
      dockerfile: Dockerfile.dev
    image: user-services
    container_name: user-services
    volumes:
      - ./UserService:/app
      - /app/node_modules
    env_file:
      - ./UserService/.env
    networks:
      - backend-network
  product-services:
    build:
      context: ./ProductService
      dockerfile: Dockerfile.dev
    image: product-services
    container_name: product-services
    volumes:
      - ./ProductService:/app
      - /app/node_modules
    env_file:
      - ./ProductService/.env
    networks:
      - backend-network
  cdn-services:
    build:
      context: ./CDNService
      dockerfile: Dockerfile
    image: cdn-services
    container_name: cdn-services
    volumes:
      - ./CDNService:/app
    env_file:
      - ./CDNService/.env
    networks:
      - backend-network
  minio-services:
    build:
      context: ./MinioBucket
      dockerfile: Dockerfile
    image: minio-services
    container_name: minio-services
    env_file:
      - ./MinioBucket/config/minio.env
    ports:
      - 9001:9001
    volumes:
      - ./MinioBucket/data:/app/data
    networks:
      - backend-network
networks:
  backend-network:
    driver: bridge
